[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.packages]
include = ["epigraph_elijahsandler"]

[tool.hatch]
root = "src"

[tool.hatch.metadata]
root = "src/epigraph_elijahsandler"

[project]
name = "epigraph-elijahsandler"
version = "0.0.8"
authors = [
    { name = "Elijah Sandler", email = "sandler.e@northeastern.edu" },
]
description = "A package for visualizing GLEAM and LEAM-US data."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
  "pandas>2.1.0",
  "plotly>5.24",
  "google-cloud-bigquery>3.0.0",
  "matplotlib>3.7.0",
  "kaleido>0.2.0"
]

[project.urls]
Homepage = "https://github.com/mattk7/viz-book-public/library"
