[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.packages]
include = ["epidemic_intelligence"]

[tool.hatch]
root = "src"

[tool.hatch.metadata]
root = "src/epidemic_intelligence"

[project]
name = "epidemic-intelligence"
version = "0.2.4"
authors = [
    { name = "Elijah Sandler", email = "sandler.e@northeastern.edu" },
]
description = "A data visualization Python package to explore large-scale spatio-temporal simulation data"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
  "pandas>2.1.0",
  "plotly>5.24",
  "google-cloud-bigquery>3.0.0",
  "matplotlib>3.7.0",
  "kaleido",
  "db-dtypes>1.0.0"
]

[project.urls]
Homepage = "https://github.com/mattk7/viz-book-public/library"
