[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "epigraph-elijahsandler"
version = "0.0.1"
authors = [
  { name="Elijah Sandler", email="sandler.e@northeastern.edu" },
]
description = "A package for visualizing GLEAM and LEAM-US data."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/mattk7/viz-book-public/library"

[project.dependencies]
pandas = "^2.1.3"
plotly = "^5.24"
etc.
