name: Deploy Jupyter Book to GitHub Pages

# this is the workflow trigger, commit it out to prevent site from updating on push
# on:
#   push:
#     branches:
#       - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r handbook/requirements.txt
        pip install jupyter-book ghp-import

    # Create the Google Cloud credentials file from the secret
    - name: Create Google Credentials File
      run: |
        echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > $HOME/google-credentials.json
      shell: bash

    # Set the environment variable to point to the generated credentials file
    - name: Set Google Application Credentials
      run: |
        export GOOGLE_APPLICATION_CREDENTIALS="$HOME/google-credentials.json"

    - name: Build Jupyter Book
      run: |
        cd handbook
        jupyter-book build .

    - name: Deploy to GitHub Pages
      run: |
        ghp-import -n -p -f handbook/_build/html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
